Repository MeetYourBook/meet-your-book, pull requests merged in 2024-09, with the labels that each got.

#74 [FE] 코드 리팩터링: 가독성 및 코드 품질 개선을 위한 전반적인 리팩터링
  fe/src/components/BooksDisplay/BookCard/BookCard.tsx
  fe/src/components/BooksDisplay/BooksDisplay.tsx
  fe/src/components/FilterDisplay/LibraryFilter/LibraryFilter.tsx
  fe/src/components/FilterDisplay/LibraryList/LibraryList.tsx
  fe/src/components/Layout/DefaultLayout.tsx
  fe/src/components/LoadingFallBack/LoadingFallBack.tsx
  fe/src/components/Modal/BookInfoModal/BookInfoModal.tsx
  fe/src/components/Modal/LibrariesPaging/LibrariesPaging.tsx
  fe/src/components/Navigation/Logo/Logo.tsx
  fe/src/components/Navigation/MobileSearchFilterPanel/MobileSearchFilterPanel.tsx
  fe/src/components/Navigation/Navigation.tsx
  fe/src/hooks/useFilterSearch.tsx
  fe/src/hooks/useGenerateQuery.tsx
  fe/src/hooks/useLibraryFilter.tsx
  fe/src/pages/Layout.tsx
  fe/src/pages/Login.tsx
  fe/src/pages/SignUp.tsx
  fe/src/routers/routes.tsx
  fe/src/tests/componentsTests/BookInfoModal.test.tsx
  fe/src/tests/componentsTests/LibrariesPaging.test.tsx
  fe/src/tests/componentsTests/LibraryFilter.test.tsx
  fe/src/tests/componentsTests/Logo.test.tsx
  fe/src/tests/hooksTests/useLibraryFilter.test.tsx
  fe/src/tests/pagesTests/Layout.test.tsx
  fe/src/utils/index.ts
Labels: enhancement, FE, refactor

#80 [BE] liquibase 의존성 추가 및 provider 필드 조정
  .github/workflows/sonarcloud-analysis.yml
  be/ebook-search/buildSrc/build.gradle
  be/ebook-search/buildSrc/src/main/groovy/java-common-conventions.gradle
  be/ebook-search/ebook-crawler/src/main/java/com/meetyourbook/crawler/BookPageProcessor.java
  be/ebook-search/ebook-crawler/src/main/java/com/meetyourbook/dto/BookRecord.java
  be/ebook-search/ebook-crawler/src/main/java/com/meetyourbook/repository/BookJdbcRepository.java
  be/ebook-search/ebook-crawler/src/test/java/com/meetyourbook/repository/BookJdbcRepositoryTest.java
  be/ebook-search/ebook-crawler/src/test/java/com/meetyourbook/repository/BookLibraryJdbcRepositoryTest.java
  be/ebook-search/ebook-crawler/src/test/java/com/meetyourbook/service/LibraryImportServiceTest.java
  be/ebook-search/ebook-crawler/src/test/resources/application.yml
  be/ebook-search/ebook-domain/src/main/java/com/meetyourbook/dto/BookCreationInfo.java
  be/ebook-search/ebook-domain/src/main/java/com/meetyourbook/dto/BookInfo.java
  be/ebook-search/ebook-domain/src/main/java/com/meetyourbook/dto/SimpleBookResponse.java
  be/ebook-search/ebook-domain/src/main/java/com/meetyourbook/entity/Book.java
  be/ebook-search/ebook-domain/src/main/java/com/meetyourbook/entity/Library.java
  be/ebook-search/ebook-domain/src/main/resources/db/changelog/changelog-1.0.sql
  be/ebook-search/ebook-domain/src/main/resources/db/changelog/changelog-root.yml
  be/ebook-search/ebook-web/src/main/java/com/meetyourbook/dto/BookCreateRequest.java
  be/ebook-search/ebook-web/src/test/java/com/meetyourbook/controller/BookControllerTest.java
  be/ebook-search/ebook-web/src/test/java/com/meetyourbook/controller/admin/AdminBookControllerTest.java
Labels: enhancement, BE, Build

#82 [BE] ec2에 nginx 컨테이너를 띄우기 위해 workflow 수정
  .github/workflows/deploy-web.yml
Labels: CI/CD

#85 [BE] 전자도서관 플랫폼별로 도서관을 크롤링하는 기능 구현
  be/ebook-search/ebook-crawler/src/docs/asciidoc/book-crawler.adoc
  be/ebook-search/ebook-crawler/src/docs/asciidoc/index.adoc
  be/ebook-search/ebook-crawler/src/docs/asciidoc/library-crawler.adoc
  be/ebook-search/ebook-crawler/src/main/java/com/meetyourbook/common/annotation/EbookPlatformCrawler.java
  be/ebook-search/ebook-crawler/src/main/java/com/meetyourbook/controller/LibraryCrawlerController.java
  be/ebook-search/ebook-crawler/src/main/java/com/meetyourbook/crawler/library/EbookPlatformLibraryCrawler.java
  be/ebook-search/ebook-crawler/src/main/java/com/meetyourbook/crawler/library/KyoboLibraryCrawler.java
  be/ebook-search/ebook-crawler/src/main/java/com/meetyourbook/crawler/library/LibraryCrawlerFactory.java
  be/ebook-search/ebook-crawler/src/main/java/com/meetyourbook/dto/EbookPlatformCrawlRequest.java
  be/ebook-search/ebook-crawler/src/main/java/com/meetyourbook/dto/ImportResult.java
  be/ebook-search/ebook-crawler/src/main/java/com/meetyourbook/dto/LibraryCrawlResult.java
  be/ebook-search/ebook-crawler/src/main/java/com/meetyourbook/dto/LibraryCrawlerTarget.java
  be/ebook-search/ebook-crawler/src/main/java/com/meetyourbook/service/LibraryCrawlerService.java
  be/ebook-search/ebook-crawler/src/main/java/com/meetyourbook/service/LibraryImportService.java
  be/ebook-search/ebook-crawler/src/main/java/com/meetyourbook/util/EbookPlatformUrlProperties.java
  be/ebook-search/ebook-crawler/src/test/java/com/meetyourbook/controller/LibraryCrawlerControllerTest.java
  be/ebook-search/ebook-crawler/src/test/java/com/meetyourbook/crawler/library/LibraryCrawlerFactoryTest.java
  be/ebook-search/ebook-crawler/src/test/java/com/meetyourbook/util/EbookPlatformUrlPropertiesTest.java
  be/ebook-search/ebook-crawler/src/test/resources/ebook-config.properties
  be/ebook-search/ebook-domain/src/main/java/com/meetyourbook/dto/BookSearchInfo.java
  be/ebook-search/ebook-domain/src/main/java/com/meetyourbook/dto/DuplicateLibrary.java
  be/ebook-search/ebook-domain/src/main/java/com/meetyourbook/dto/LibraryCreationInfo.java
  be/ebook-search/ebook-domain/src/main/java/com/meetyourbook/dto/LibraryCreationResult.java
  be/ebook-search/ebook-domain/src/main/java/com/meetyourbook/entity/Library.java
  be/ebook-search/ebook-domain/src/main/java/com/meetyourbook/entity/LibraryUrl.java
  be/ebook-search/ebook-domain/src/main/java/com/meetyourbook/service/LibraryDomainService.java
  be/ebook-search/ebook-domain/src/main/resources/db/changelog/changelog-1.0.sql
  be/ebook-search/ebook-domain/src/test/java/com/meetyourbook/service/LibraryDomainServiceTest.java
  be/ebook-search/ebook-web/src/docs/asciidoc/index.adoc
  be/ebook-search/ebook-web/src/main/java/com/meetyourbook/controller/BookController.java
  be/ebook-search/ebook-web/src/main/java/com/meetyourbook/dto/BookSearchRequest.java
  be/ebook-search/ebook-web/src/main/java/com/meetyourbook/dto/LibraryCreateRequest.java
Labels: enhancement, BE

#87 [FE] api 연결 및 mock 데이터와 타입이 다른 에러 수정
  fe/src/components/BooksDisplay/BookCard/BookCard.tsx
  fe/src/components/FilterDisplay/LibraryFilter/LibraryFilter.tsx
  fe/src/components/FilterDisplay/LibraryList/LibraryList.tsx
  fe/src/components/Modal/LibrariesPaging/LibrariesPaging.tsx
  fe/src/constants/index.ts
  fe/src/hooks/useFilterSearch.tsx
  fe/src/hooks/useLibraryFilter.tsx
  fe/src/stories/Navigation.stories.tsx
  fe/src/styles/BookCardStyle.ts
  fe/src/styles/FilterDisplay.ts
  fe/src/styles/LibraryListStyle.ts
  fe/src/tests/componentsTests/LibrariesPaging.test.tsx
  fe/src/tests/componentsTests/LibraryFilter.test.tsx
  fe/src/tests/hooksTests/useLibraryFilter.test.tsx
  fe/src/tests/pagesTests/Layout.test.tsx
  fe/src/types/Books.ts
  fe/src/types/LibrariesResponse.ts
  fe/src/types/PageNation.ts
  fe/vite.config.ts
Labels: enhancement, FE, testing

#89 [BE] Book 엔티티의 ID를 UUID 에서 Long 으로 변경
  be/ebook-search/ebook-crawler/src/main/java/com/meetyourbook/dto/BookLibraryRelation.java
  be/ebook-search/ebook-crawler/src/main/java/com/meetyourbook/repository/BookJdbcRepository.java
  be/ebook-search/ebook-crawler/src/main/java/com/meetyourbook/repository/BookLibraryJdbcRepository.java
  be/ebook-search/ebook-crawler/src/main/java/com/meetyourbook/service/BookCacheService.java
  be/ebook-search/ebook-crawler/src/main/java/com/meetyourbook/service/BookLibraryService.java
  be/ebook-search/ebook-crawler/src/test/java/com/meetyourbook/repository/BookJdbcRepositoryTest.java
  be/ebook-search/ebook-crawler/src/test/java/com/meetyourbook/repository/BookLibraryJdbcRepositoryTest.java
  be/ebook-search/ebook-domain/src/main/java/com/meetyourbook/dto/SimpleBookResponse.java
  be/ebook-search/ebook-domain/src/main/java/com/meetyourbook/entity/Book.java
  be/ebook-search/ebook-domain/src/main/java/com/meetyourbook/repository/BookRepository.java
  be/ebook-search/ebook-domain/src/main/java/com/meetyourbook/service/BookDomainService.java
  be/ebook-search/ebook-domain/src/main/java/com/meetyourbook/spec/BookSpecs.java
  be/ebook-search/ebook-domain/src/main/resources/db/changelog/changelog-1.0.sql
  be/ebook-search/ebook-domain/src/test/java/com/meetyourbook/service/BookDomainServiceTest.java
  be/ebook-search/ebook-web/src/main/java/com/meetyourbook/controller/admin/AdminBookController.java
  be/ebook-search/ebook-web/src/main/java/com/meetyourbook/service/BookService.java
  be/ebook-search/ebook-web/src/test/java/com/meetyourbook/controller/BookControllerTest.java
  be/ebook-search/ebook-web/src/test/java/com/meetyourbook/controller/admin/AdminBookControllerTest.java
Labels: documentation, BE, refactor

#91 [FE] CI/CD 구축 및 크로메틱 배포 에러 수정
  .github/workflows/chromatic.yml
  .github/workflows/deploy.yml
  fe/.gitignore
  fe/src/components/FilterDisplay/LibraryFilter/LibraryFilter.tsx
  fe/src/main.tsx
  fe/src/mocks/mockData/books.json
  fe/src/mocks/mockData/library.json
Labels: bug, FE, CI/CD, Build

#93 [FE] 다크모드 기능 구현
  .github/workflows/chromatic.yml
  fe/src/components/FilterDisplay/LibraryFilter/LibraryFilter.tsx
  fe/src/components/Layout/DefaultLayout.tsx
  fe/src/components/Navigation/MobileSearchFilterPanel/MobileSearchFilterPanel.tsx
  fe/src/components/Navigation/SearchInput/SearchInput.tsx
  fe/src/components/Navigation/ThemeSwitcher/ThemeSwitcher.tsx
  fe/src/hooks/useThemeContext.tsx
  fe/src/main.tsx
  fe/src/mocks/handlers/booksHandler.ts
  fe/src/mocks/handlers/index.ts
  fe/src/mocks/handlers/libraryHandler.ts
  fe/src/styles/BookCardStyle.ts
  fe/src/styles/BookDisplayStyle.ts
  fe/src/styles/BookInfoModalStyle.ts
  fe/src/styles/DropDownStyle.ts
  fe/src/styles/GlobalStyle.ts
  fe/src/styles/LibrariesPagingStyle.ts
  fe/src/styles/LibraryFilterStyle.ts
  fe/src/styles/MobileSearchFilterPanelStyle.ts
  fe/src/styles/NavigationStyle.ts
  fe/src/styles/SearchInputStyle.ts
  fe/src/styles/Theme.ts
  fe/src/styles/ViewSelectorStyle.ts
  fe/src/tests/componentsTests/SearchInput.test.tsx
  fe/src/tests/pagesTests/Layout.test.tsx
  fe/vite.config.ts
Labels: enhancement, FE

#95 [FE] 즐겨찾기 기능 구현
  fe/src/components/BackButton/BackButton.tsx
  fe/src/components/BooksDisplay/BookCard/BookCard.tsx
  fe/src/components/FavoriteBtn/FavoriteBtn.tsx
  fe/src/components/FilterDisplay/LibraryList/LibraryList.tsx
  fe/src/components/Navigation/ThemeSwitcher/ThemeSwitcher.tsx
  fe/src/hooks/useThemeContext.tsx
  fe/src/pages/Login.tsx
  fe/src/pages/SignUp.tsx
  fe/src/routers/routes.tsx
  fe/src/stories/Login.stories.tsx
  fe/src/stories/SignUp.stories.tsx
  fe/src/styles/BookCardStyle.ts
  fe/src/styles/LibrariesPagingStyle.ts
  fe/src/styles/LibraryListStyle.ts
  fe/src/tests/componentsTests/ FavoriteBtn.test.tsx
  fe/src/tests/componentsTests/BookCard.test.tsx
  fe/src/tests/componentsTests/ErrorFallBack.test.tsx
  fe/src/utils/index.ts
  fe/src/vite-env.d.ts
  fe/tsconfig.app.json
  fe/vite.config.ts
Labels: enhancement, FE

#96 [BE] Crawler 모듈을 위한 배포 설정
  .github/workflows/deploy-crawler.yml
  be/ebook-search/ebook-crawler/Dockerfile
  be/ebook-search/ebook-crawler/src/main/java/com/meetyourbook/util/EbookPlatformUrlProperties.java
Labels: BE, CI/CD

#99 [BE] EntityGraph를 삭제해서 heap 메모리 이슈 해결
  be/ebook-search/ebook-domain/src/main/java/com/meetyourbook/repository/BookRepository.java
Labels: bug, BE

#100 [FE] 어드민 로그인 구현
  fe/.storybook/preview.tsx
  fe/src/constants/index.ts
  fe/src/hooks/queries/useBooksQuery.tsx
  fe/src/hooks/queries/useLibrariesQuery.tsx
  fe/src/hooks/queries/useLoginMutation.tsx
  fe/src/hooks/useBooksLogic.tsx
  fe/src/hooks/useGenerateQuery.tsx
  fe/src/hooks/useLibraryFilter.tsx
  fe/src/hooks/useQueryData.tsx
  fe/src/main.tsx
  fe/src/mocks/handlers/index.ts
  fe/src/mocks/handlers/loginHandler.ts
  fe/src/mocks/mockData/login.json
  fe/src/mocks/node.ts
  fe/src/pages/Admin.tsx
  fe/src/pages/Login.tsx
  fe/src/routers/routes.tsx
  fe/src/services/APIClient.ts
  fe/src/services/APIOptions.ts
  fe/src/services/fetch.ts
  fe/src/services/index.ts
  fe/src/styles/AuthFormStyle.ts
  fe/src/tests/componentsTests/BookDisplay.test.tsx
  fe/src/tests/componentsTests/FavoriteBtn.test.tsx
  fe/src/tests/hooksTests/useGeneratequery.test.ts
  fe/src/tests/hooksTests/useLibraryFilter.test.tsx
  fe/src/tests/pagesTests/Login.test.tsx
  fe/vite.config.ts
Labels: enhancement, FE

#101 [BE] 책 응답에 누락된 출판일 추가
  be/ebook-search/ebook-domain/src/main/java/com/meetyourbook/dto/SimpleBookResponse.java
  be/ebook-search/ebook-web/src/test/java/com/meetyourbook/controller/BookControllerTest.java
Labels: bug, BE

#98 [BE] 크롤링 후 저장과정에서 트랜잭션 개선
  be/ebook-search/ebook-crawler/build.gradle
  be/ebook-search/ebook-crawler/src/main/java/com/meetyourbook/repository/BookJdbcRepository.java
  be/ebook-search/ebook-crawler/src/main/java/com/meetyourbook/service/BookCacheService.java
  be/ebook-search/ebook-crawler/src/test/resources/application.yml
  be/ebook-search/ebook-domain/build.gradle
  be/ebook-search/ebook-domain/src/main/java/com/meetyourbook/dto/BookLibraryRelation.java
  be/ebook-search/ebook-domain/src/main/java/com/meetyourbook/dto/BookRecord.java
  be/ebook-search/ebook-domain/src/main/java/com/meetyourbook/dto/BookUniqueKey.java
  be/ebook-search/ebook-domain/src/main/java/com/meetyourbook/repository/jdbc/BookJdbcRepository.java
  be/ebook-search/ebook-domain/src/main/java/com/meetyourbook/repository/jdbc/BookLibraryJdbcRepository.java
  be/ebook-search/ebook-domain/src/main/java/com/meetyourbook/repository/jpa/BookLibraryRepository.java
  be/ebook-search/ebook-domain/src/main/java/com/meetyourbook/repository/jpa/BookRepository.java
  be/ebook-search/ebook-domain/src/main/java/com/meetyourbook/repository/jpa/LibraryRepository.java
  be/ebook-search/ebook-domain/src/main/java/com/meetyourbook/service/BookCountVerificationService.java
  be/ebook-search/ebook-domain/src/main/java/com/meetyourbook/service/BookDomainService.java
  be/ebook-search/ebook-domain/src/main/java/com/meetyourbook/service/BookLibraryService.java
  be/ebook-search/ebook-domain/src/main/java/com/meetyourbook/service/BookPersistenceService.java
  be/ebook-search/ebook-domain/src/main/java/com/meetyourbook/service/LibraryCacheService.java
  be/ebook-search/ebook-domain/src/main/java/com/meetyourbook/service/LibraryDomainService.java
  be/ebook-search/ebook-domain/src/test/java/com/meetyourbook/common/JdbcRepositoryTest.java
  be/ebook-search/ebook-domain/src/test/java/com/meetyourbook/common/JpaRepositoryTest.java
  be/ebook-search/ebook-domain/src/test/java/com/meetyourbook/common/config/TestJdbcConfig.java
  be/ebook-search/ebook-domain/src/test/java/com/meetyourbook/common/config/TestJpaConfig.java
  be/ebook-search/ebook-domain/src/test/java/com/meetyourbook/repository/jdbc/BookJdbcRepositoryTest.java
  be/ebook-search/ebook-domain/src/test/java/com/meetyourbook/repository/jdbc/BookLibraryJdbcRepositoryTest.java
  be/ebook-search/ebook-domain/src/test/java/com/meetyourbook/repository/jpa/BookLibraryRepositoryTest.java
  be/ebook-search/ebook-domain/src/test/java/com/meetyourbook/repository/jpa/BookRepositoryTest.java
  be/ebook-search/ebook-domain/src/test/java/com/meetyourbook/service/BookDomainServiceTest.java
  be/ebook-search/ebook-domain/src/test/java/com/meetyourbook/service/LibraryDomainServiceTest.java
Labels: BE, refactor

#102 [FE]: 검색 및 필터 상태 시각화를 위한 FilterStatusBar 컴포넌트 추가
  fe/index.html
  fe/public/images/favicon.ico
  fe/src/components/Admin/ItmeManager/ItemManager.tsx
  fe/src/components/BooksDisplay/BooksDisplay.tsx
  fe/src/components/FilterDisplay/LibraryList/LibraryList.tsx
  fe/src/components/Layout/DefaultLayout.tsx
  fe/src/components/Layout/PrivateAdminLayout.tsx
  fe/src/components/Navigation/DropDownBox/DropDownBox.tsx
  fe/src/components/Navigation/FilterStatusBar/FilterStatusBar.tsx
  fe/src/components/Navigation/SearchInput/SearchInput.tsx
  fe/src/constants/index.ts
  fe/src/hooks/useBooksLogic.tsx
  fe/src/hooks/useGenerateQuery.tsx
  fe/src/hooks/useLibraryFilter.tsx
  fe/src/main.tsx
  fe/src/mocks/mockData/login.json
  fe/src/pages/Admin.tsx
  fe/src/pages/Login.tsx
  fe/src/routers/routes.tsx
  fe/src/stores/queryStore.ts
  fe/src/styles/AdinPageStyle.ts
  fe/src/styles/BookDisplayStyle.ts
  fe/src/styles/BookInfoModalStyle.ts
  fe/src/styles/LibraryFilterStyle.ts
  fe/src/styles/MobileSearchFilterPanelStyle.ts
  fe/src/styles/NavigationStyle.ts
  fe/src/tests/componentsTests/BookCard.test.tsx
  fe/src/tests/componentsTests/BookDisplay.test.tsx
  fe/src/tests/componentsTests/DropDownBox.test.tsx
  fe/src/tests/componentsTests/FilterStatusBar.test.tsx
  fe/src/tests/componentsTests/SearchInput.test.tsx
  fe/src/tests/hooksTests/useGeneratequery.test.ts
  fe/src/tests/pagesTests/Login.test.tsx
  fe/src/types/Admin.ts
Labels: enhancement, FE

#106 [BE] BookPageProcessor로부터 교보문고 파싱 기능 분리
  be/ebook-search/ebook-crawler/src/main/java/com/meetyourbook/config/KyoboParserConfig.java
  be/ebook-search/ebook-crawler/src/main/java/com/meetyourbook/crawler/BookPageProcessor.java
  be/ebook-search/ebook-crawler/src/main/java/com/meetyourbook/parser/BookPageParser.java
  be/ebook-search/ebook-crawler/src/main/java/com/meetyourbook/parser/KyoboParser.java
  be/ebook-search/ebook-crawler/src/test/java/com/meetyourbook/crawler/BookPageConcurrencyTest.java
  be/ebook-search/ebook-crawler/src/test/java/com/meetyourbook/crawler/BookPageProcessorTest.java
  be/ebook-search/ebook-crawler/src/test/java/com/meetyourbook/parser/KyoboParserTest.java
Labels: BE, refactor

#107 [BE] Dockerfile에 환경변수값 추가
  be/ebook-search/ebook-crawler/Dockerfile
  be/ebook-search/ebook-domain/src/main/java/com/meetyourbook/dto/LibraryCreationInfo.java
Labels: BE, Build

#108 [FE]: 브라우저 호환성 개선 및 레이아웃 스타일링, 클라우드프론트 캐싱 처리
  fe/src/components/BooksDisplay/BookCard/BookCard.tsx
  fe/src/components/Modal/BookInfoModal/BookInfoModal.tsx
  fe/src/hooks/queries/useBooksQuery.tsx
  fe/src/hooks/queries/useLibrariesQuery.tsx
  fe/src/styles/BookCardStyle.ts
  fe/src/styles/BookInfoModalStyle.ts
  fe/src/styles/LibraryFilterStyle.ts
  fe/src/styles/LibraryListStyle.ts
  fe/src/tests/componentsTests/BookCard.test.tsx
  fe/src/tests/componentsTests/BookInfoModal.test.tsx
  fe/src/types/Books.ts
Labels: enhancement, FE

#110 [FE] SEO 개선
  fe/index.html
  fe/public/images/logo.png
  fe/public/robots.txt
  fe/public/sitemap.xml
  fe/src/mocks/mockData/books.json
Labels: enhancement, FE
