Repository MeetYourBook/meet-your-book, pull requests merged in 2024-08, with the labels that each got.

#12 크롤러를 시작하고 멈추는 api 구현
  be/ebook-search/ebook-crawler/src/main/java/com/meetyourbook/controller/BookCrawlerController.java
  be/ebook-search/ebook-crawler/src/main/java/com/meetyourbook/crawler/BookPageProcessor.java
  be/ebook-search/ebook-crawler/src/main/java/com/meetyourbook/dto/CrawlerRequest.java
  be/ebook-search/ebook-crawler/src/main/java/com/meetyourbook/service/BookCrawlerService.java
  be/ebook-search/ebook-crawler/src/test/java/com/meetyourbook/service/BookCrawlerServiceTest.java
Labels: enhancement, BE

#11 책 검색 기능 구현
  be/ebook-search/ebook-core/src/main/java/com/meetyourbook/controller/BookController.java
  be/ebook-search/ebook-core/src/main/java/com/meetyourbook/dto/BookInfo.java
  be/ebook-search/ebook-core/src/main/java/com/meetyourbook/dto/BookLibraryResponse.java
  be/ebook-search/ebook-core/src/main/java/com/meetyourbook/dto/BookSearchRequest.java
  be/ebook-search/ebook-core/src/main/java/com/meetyourbook/dto/Condition.java
  be/ebook-search/ebook-core/src/main/java/com/meetyourbook/dto/SimpleBookResponse.java
  be/ebook-search/ebook-core/src/main/java/com/meetyourbook/entity/BookLibrary.java
  be/ebook-search/ebook-core/src/main/java/com/meetyourbook/repository/BookRepository.java
  be/ebook-search/ebook-core/src/main/java/com/meetyourbook/service/BookLibraryService.java
  be/ebook-search/ebook-core/src/main/java/com/meetyourbook/service/BookService.java
Labels: enhancement, BE

#18 [BE] 책 검색 API 개선
  be/ebook-search/ebook-core/src/main/java/com/meetyourbook/dto/BookSearchRequest.java
  be/ebook-search/ebook-core/src/main/java/com/meetyourbook/entity/BookLibrary.java
  be/ebook-search/ebook-core/src/main/java/com/meetyourbook/repository/BookRepository.java
  be/ebook-search/ebook-core/src/main/java/com/meetyourbook/service/BookLibraryService.java
  be/ebook-search/ebook-core/src/main/java/com/meetyourbook/service/BookService.java
  be/ebook-search/ebook-core/src/main/java/com/meetyourbook/spec/BookSpecs.java
  be/ebook-search/ebook-core/src/main/java/com/meetyourbook/spec/SpecBuilder.java
  be/ebook-search/ebook-core/src/test/java/com/meetyourbook/repository/BookRepositoryTest.java
Labels: enhancement, BE, testing, refactor

#20 [FE] CSS styled-component로 변경 및 storybook, vitest, msw setup
  fe/.eslintrc.cjs
  fe/.gitignore
  fe/.storybook/main.ts
  fe/.storybook/preview.ts
  fe/package-lock.json
  fe/package.json
  fe/public/mockServiceWorker.js
  fe/src/components/Button/CountButton.tsx
  fe/src/components/Navigation/Navigation.tsx
  fe/src/main.tsx
  fe/src/mocks/handlers.ts
  fe/src/mocks/node.ts
  fe/src/pages/Home.tsx
  fe/src/pages/Layout.tsx
  fe/src/stories/button.stories.ts
  fe/src/styles/NavagationStyle.ts
  fe/src/tests/countButton.test.tsx
  fe/src/tests/setup.ts
  fe/tsconfig.app.json
  fe/tsconfig.json
  fe/vite.config.ts
Labels: bug, FE, testing, refactor

#21 [FE] Layout 네비게이션 컴포넌트 기능 추가
  fe/.gitignore
  fe/package-lock.json
  fe/package.json
  fe/src/components/Button/CountButton.tsx
  fe/src/components/Navigation/DropDownBox/DropDownBox.tsx
  fe/src/components/Navigation/Navigation.tsx
  fe/src/components/Navigation/SearchInput/SearchInput.tsx
  fe/src/index.css
  fe/src/main.tsx
  fe/src/stories/DropDownBox.stories.tsx
  fe/src/stories/SearchInput.stories.tsx
  fe/src/styles/DropDownStyle.ts
  fe/src/styles/GlobalStyle.ts
  fe/src/styles/NavagationStyle.ts
  fe/src/styles/NavigationStyle.ts
  fe/src/styles/SearchInputStyle.ts
  fe/src/tests/DropDownBox.test.tsx
  fe/src/tests/NavContainer.test.tsx
  fe/src/tests/SearchInput.test.tsx
  fe/src/tests/countButton.test.tsx
Labels: enhancement, FE

#25 [FE] storybook ci/cd 구축
  .github/workflows/chromatic.yml
  fe/package-lock.json
  fe/package.json
  fe/src/stories/Navigation.stories.tsx
Labels: FE

#27 [FE] 스토리북 ci/cd 적용
  .github/workflows/chromatic.yml
  fe/package.json
Labels: enhancement

#19 [BE] SonarCloud 적용 및 Cralwer API 구현
  .github/workflows/build.yml
  be/ebook-search/build.gradle
  be/ebook-search/buildSrc/build.gradle
  be/ebook-search/buildSrc/src/main/groovy/com.meetyourbook.java-common-conventions.gradle
  be/ebook-search/ebook-core/build.gradle
  be/ebook-search/ebook-core/src/main/java/com/meetyourbook/EbookCoreApplication.java
  be/ebook-search/ebook-core/src/test/resources/application.yaml
  be/ebook-search/ebook-crawler/build.gradle
  be/ebook-search/ebook-crawler/src/main/java/com/meetyourbook/common/config/AsyncConfig.java
  be/ebook-search/ebook-crawler/src/main/java/com/meetyourbook/common/config/MetricsConfig.java
  be/ebook-search/ebook-crawler/src/main/java/com/meetyourbook/common/exception/CrawlerAlreadyRunningException.java
  be/ebook-search/ebook-crawler/src/main/java/com/meetyourbook/common/exception/CrawlerException.java
  be/ebook-search/ebook-crawler/src/main/java/com/meetyourbook/common/exception/CrawlerExceptionHandler.java
  be/ebook-search/ebook-crawler/src/main/java/com/meetyourbook/common/exception/CrawlerNotRunningException.java
  be/ebook-search/ebook-crawler/src/main/java/com/meetyourbook/controller/BookCrawlerController.java
  be/ebook-search/ebook-crawler/src/main/java/com/meetyourbook/crawler/BookCountProcessor.java
  be/ebook-search/ebook-crawler/src/main/java/com/meetyourbook/crawler/BookCrawlerRunner.java
  be/ebook-search/ebook-crawler/src/main/java/com/meetyourbook/crawler/BookPageProcessor.java
  be/ebook-search/ebook-crawler/src/main/java/com/meetyourbook/crawler/ProcessorFactory.java
  be/ebook-search/ebook-crawler/src/main/java/com/meetyourbook/crawler/ProcessorType.java
  be/ebook-search/ebook-crawler/src/main/java/com/meetyourbook/dto/CrawlerErrorResponse.java
  be/ebook-search/ebook-crawler/src/main/java/com/meetyourbook/dto/CrawlerRequest.java
  be/ebook-search/ebook-crawler/src/main/java/com/meetyourbook/dto/CrawlerResponse.java
  be/ebook-search/ebook-crawler/src/main/java/com/meetyourbook/service/BookCrawlerService.java
  be/ebook-search/ebook-crawler/src/main/java/com/meetyourbook/service/CrawlerService.java
  be/ebook-search/ebook-crawler/src/test/java/com/meetyourbook/crawler/BookPageProcessorTest.java
  be/ebook-search/ebook-crawler/src/test/java/com/meetyourbook/crawler/ProcessorFactoryTest.java
  be/ebook-search/ebook-crawler/src/test/java/com/meetyourbook/service/BookCrawlerServiceTest.java
Labels: enhancement, BE

#28 [BE] 도서관 조회 API 구현
  be/ebook-search/ebook-core/src/main/java/com/meetyourbook/EbookCoreApplication.java
  be/ebook-search/ebook-core/src/main/java/com/meetyourbook/controller/LibraryController.java
  be/ebook-search/ebook-core/src/main/java/com/meetyourbook/dto/LibraryResponse.java
  be/ebook-search/ebook-core/src/main/java/com/meetyourbook/service/LibraryService.java
  be/ebook-search/ebook-core/src/test/java/com/meetyourbook/entity/LibraryTest.java
Labels: enhancement, BE

#31 [FE] 도서관 필터 구현 및 zustand 상태관리 적용
  .github/workflows/chromatic.yml
  fe/.gitignore
  fe/package-lock.json
  fe/package.json
  fe/src/components/BooksDisplay/BookCard/BookCard.tsx
  fe/src/components/BooksDisplay/BooksDisplay.tsx
  fe/src/components/BooksDisplay/ViewSelector/ViewSelector.tsx
  fe/src/components/FilterDisplay/FilterDisplay.tsx
  fe/src/components/FilterDisplay/LibraryFilter/LibraryFilter.tsx
  fe/src/components/Navigation/DropDownBox/DropDownBox.tsx
  fe/src/components/Navigation/SearchInput/SearchInput.tsx
  fe/src/hooks/useDebounce.tsx
  fe/src/hooks/useGenerateQuery.tsx
  fe/src/hooks/useLibraryFilter.tsx
  fe/src/main.tsx
  fe/src/mocks/handlers.ts
  fe/src/mocks/handlers/booksHandler.ts
  fe/src/mocks/handlers/libraryHandler.ts
  fe/src/mocks/node.ts
  fe/src/pages/Home.tsx
  fe/src/stores/queryStore.ts
  fe/src/styles/BookCardStyle.ts
  fe/src/styles/BookDisplayStyle.ts
  fe/src/styles/FilterDisplay.ts
  fe/src/styles/LibraryFilterStyle.ts
  fe/src/styles/NavigationStyle.ts
  fe/src/styles/ViewSelectorStyle.ts
Labels: enhancement, FE

#32 [FE] SonarCloud CI/CD 통합 및 자동 코드 품질 분석 적용
  .github/workflows/sonarcloud.yml
  fe/package.json
  fe/src/hooks/useGenerateQuery.tsx
  fe/src/styles/BookCardStyle.ts
  fe/src/tests/SearchInput.test.tsx
  fe/vite.config.ts
  sonar-project.properties
Labels: enhancement, FE

#38 [BE] 멀티 스레드로 인해서 url 저장과정에 경합이 생기는 문제 해결
  be/ebook-search/ebook-crawler/src/main/java/com/meetyourbook/crawler/BookPageProcessor.java
  be/ebook-search/ebook-crawler/src/test/java/com/meetyourbook/crawler/BookPageConcurrencyTest.java
Labels: bug, BE

#36 [BE] 책 정보 조회 시 페이징 기능 구현
  be/ebook-search/ebook-core/src/main/java/com/meetyourbook/controller/BookController.java
  be/ebook-search/ebook-core/src/main/java/com/meetyourbook/dto/BookPageResponse.java
  be/ebook-search/ebook-core/src/main/java/com/meetyourbook/repository/BookRepository.java
  be/ebook-search/ebook-core/src/main/java/com/meetyourbook/service/BookService.java
Labels: enhancement, BE

#39 [BE] 책 상세 페이지 URL을 파싱하고 저장하는 기능
  be/ebook-search/ebook-core/src/main/java/com/meetyourbook/service/BookLibraryService.java
  be/ebook-search/ebook-crawler/src/main/java/com/meetyourbook/crawler/BookPageProcessor.java
  be/ebook-search/ebook-crawler/src/test/java/com/meetyourbook/crawler/BookPageProcessorTest.java
Labels: enhancement, BE

#35 [FE] libraries 타입 변경 및 테스트 코드 작성
  fe/.storybook/main.ts
  fe/package-lock.json
  fe/package.json
  fe/src/components/BooksDisplay/BookCard/BookCard.tsx
  fe/src/components/FilterDisplay/LibraryFilter/LibraryFilter.tsx
  fe/src/hooks/useLibraryFilter.tsx
  fe/src/mocks/handlers/libraryHandler.ts
  fe/src/styles/BookCardStyle.ts
  fe/src/tests/componentsTests/ FIlterDisplay.test.tsx
  fe/src/tests/componentsTests/BookCard.test.tsx
  fe/src/tests/componentsTests/BookDisplay.test.tsx
  fe/src/tests/componentsTests/DropDownBox.test.tsx
  fe/src/tests/componentsTests/LibraryFilter.test.tsx
  fe/src/tests/componentsTests/Navgation.test.tsx
  fe/src/tests/componentsTests/SearchInput.test.tsx
  fe/src/tests/componentsTests/VIewSelectop.test.tsx
  fe/src/tests/hooksTests/useDebounce.test.tsx
  fe/src/tests/hooksTests/useLibraryFilter.test.tsx
  fe/src/tests/pagesTests/Home.test.tsx
  fe/src/tests/pagesTests/Layout.test.tsx
  fe/src/tests/pagesTests/NotFound.test.tsx
  fe/vite.config.ts
Labels: FE, testing, refactor

#41 [BE] 도서관마다 실제 책 개수와 저장된 개수를 비교하는 기능 및 api 구현
  be/ebook-search/ebook-core/src/main/java/com/meetyourbook/controller/BookVerificationController.java
  be/ebook-search/ebook-core/src/main/java/com/meetyourbook/dto/BookCountVerificationResult.java
  be/ebook-search/ebook-core/src/main/java/com/meetyourbook/repository/BookLibraryRepository.java
  be/ebook-search/ebook-core/src/main/java/com/meetyourbook/service/BookCountVerificationService.java
  be/ebook-search/ebook-core/src/test/java/com/meetyourbook/repository/BookLibraryRepositoryTest.java
Labels: enhancement, BE

#42 [FE] feat: 필터 기능 구현
  fe/.storybook/main.ts
  fe/.storybook/preview.ts
  fe/package-lock.json
  fe/package.json
  fe/src/components/BooksDisplay/BookCard/BookCard.tsx
  fe/src/components/BooksDisplay/BooksDisplay.tsx
  fe/src/components/BooksDisplay/ViewSelector/ViewSelector.tsx
  fe/src/components/FilterDisplay/LibraryFilter/LibraryFilter.tsx
  fe/src/components/FilterDisplay/LibraryFilter/LibraryList.tsx
  fe/src/components/Navigation/DropDownBox/DropDownBox.tsx
  fe/src/constants/index.ts
  fe/src/hooks/useGenerateQuery.tsx
  fe/src/hooks/useLibraryFilter.tsx
  fe/src/hooks/useQueryData.tsx
  fe/src/index.css
  fe/src/main.tsx
  fe/src/mocks/handlers/booksHandler.ts
  fe/src/services/APIOptions.ts
  fe/src/services/fetch.ts
  fe/src/stores/queryStore.ts
  fe/src/stories/DropDownBox.stories.tsx
  fe/src/stories/Navigation.stories.tsx
  fe/src/stories/SearchInput.stories.tsx
  fe/src/styles/GlobalStyle.ts
  fe/src/styles/LibraryFilterStyle.ts
  fe/src/styles/LibraryListStyle.ts
  fe/src/tests/componentsTests/BookCard.test.tsx
  fe/src/tests/componentsTests/BookDisplay.test.tsx
  fe/src/tests/componentsTests/DropDownBox.test.tsx
  fe/src/tests/componentsTests/FIlterDisplay.test.tsx
  fe/src/tests/componentsTests/LibraryFilter.test.tsx
  fe/src/tests/hooksTests/useGeneratequery.test.ts
  fe/src/tests/hooksTests/useLibraryFilter.test.tsx
  fe/src/types/Books.ts
  fe/src/types/DropDown.ts
  fe/src/types/Libraries.ts
  fe/src/types/View.ts
Labels: enhancement, FE, refactor

#45 [BE] 책, 도서관 CRUD API 구현
  be/ebook-search/ebook-core/src/main/java/com/meetyourbook/controller/BookController.java
  be/ebook-search/ebook-core/src/main/java/com/meetyourbook/controller/LibraryController.java
  be/ebook-search/ebook-core/src/main/java/com/meetyourbook/dto/BookCreateRequest.java
  be/ebook-search/ebook-core/src/main/java/com/meetyourbook/dto/BookUpdateRequest.java
  be/ebook-search/ebook-core/src/main/java/com/meetyourbook/dto/LibraryUpdateRequest.java
  be/ebook-search/ebook-core/src/main/java/com/meetyourbook/entity/Book.java
  be/ebook-search/ebook-core/src/main/java/com/meetyourbook/entity/Library.java
  be/ebook-search/ebook-core/src/main/java/com/meetyourbook/exception/ErrorResponse.java
  be/ebook-search/ebook-core/src/main/java/com/meetyourbook/exception/GlobalExceptionHandler.java
  be/ebook-search/ebook-core/src/main/java/com/meetyourbook/exception/ResourceNotFoundException.java
  be/ebook-search/ebook-core/src/main/java/com/meetyourbook/exception/ValidationErrorResponse.java
  be/ebook-search/ebook-core/src/main/java/com/meetyourbook/service/BookService.java
  be/ebook-search/ebook-core/src/main/java/com/meetyourbook/service/LibraryService.java
  be/ebook-search/ebook-core/src/test/java/com/meetyourbook/service/BookServiceTest.java
  be/ebook-search/ebook-core/src/test/java/com/meetyourbook/service/LibraryServiceTest.java
Labels: enhancement, BE

#46 [FE] infinite scroll 구현
  .github/workflows/chromatic.yml
  fe/.storybook/preview.ts
  fe/.storybook/preview.tsx
  fe/package-lock.json
  fe/package.json
  fe/public/images/errorImg.png
  fe/src/components/BooksDisplay/BookCard/BookCard.tsx
  fe/src/components/BooksDisplay/BooksDisplay.tsx
  fe/src/components/Navigation/DropDownBox/DropDownBox.tsx
  fe/src/components/Navigation/SearchInput/SearchInput.tsx
  fe/src/constants/index.ts
  fe/src/hooks/useBooksLogic.tsx
  fe/src/hooks/useGenerateQuery.tsx
  fe/src/hooks/useInfiniteScroll.tsx
  fe/src/hooks/useLibraryFilter.tsx
  fe/src/hooks/useQueryData.tsx
  fe/src/main.tsx
  fe/src/mocks/handlers/booksHandler.ts
  fe/src/mocks/handlers/libraryHandler.ts
  fe/src/mocks/node.ts
  fe/src/pages/Home.tsx
  fe/src/stores/queryStore.ts
  fe/src/stories/BookDisplay.stories.tsx
  fe/src/stories/LibraryFilter.stories.tsx
  fe/src/stories/Navigation.stories.tsx
  fe/src/styles/BookDisplayStyle.ts
  fe/src/styles/FilterDisplay.ts
  fe/src/styles/GlobalStyle.ts
  fe/src/styles/LibraryFilterStyle.ts
  fe/src/styles/NavigationStyle.ts
  fe/src/styles/font.css
  fe/src/tests/componentsTests/BookDisplay.test.tsx
  fe/src/tests/componentsTests/LibraryFilter.test.tsx
  fe/src/tests/componentsTests/SearchInput.test.tsx
  fe/src/tests/hooksTests/useLibraryFilter.test.tsx
  fe/vite.config.ts
Labels: enhancement, FE

#51 [BE] crawler api 문서화 작업을 restdoc으로 변경
  be/ebook-search/buildSrc/src/main/groovy/api-test-conventions.gradle
  be/ebook-search/ebook-crawler/src/docs/asciidoc/index.adoc
  be/ebook-search/ebook-crawler/src/main/java/com/meetyourbook/common/exception/CrawlerExceptionHandler.java
  be/ebook-search/ebook-crawler/src/main/java/com/meetyourbook/controller/BookCrawlerController.java
  be/ebook-search/ebook-crawler/src/test/java/com/meetyourbook/controller/BookCrawlerControllerTest.java
Labels: documentation, BE, testing

#56 [BE] web 모듈에 restdoc 적용
  be/ebook-search/ebook-crawler/src/test/java/com/meetyourbook/controller/BookCrawlerControllerTest.java
  be/ebook-search/ebook-domain/src/main/java/com/meetyourbook/dto/BookCountVerificationResult.java
  be/ebook-search/ebook-domain/src/main/java/com/meetyourbook/dto/BookLibraryResponse.java
  be/ebook-search/ebook-domain/src/main/java/com/meetyourbook/dto/BookPageResponse.java
  be/ebook-search/ebook-domain/src/main/java/com/meetyourbook/dto/SimpleBookResponse.java
  be/ebook-search/ebook-web/src/docs/asciidoc/book.adoc
  be/ebook-search/ebook-web/src/docs/asciidoc/index.adoc
  be/ebook-search/ebook-web/src/docs/asciidoc/library.adoc
  be/ebook-search/ebook-web/src/main/java/com/meetyourbook/controller/LibraryController.java
  be/ebook-search/ebook-web/src/test/java/com/meetyourbook/controller/BookControllerTest.java
  be/ebook-search/ebook-web/src/test/java/com/meetyourbook/controller/BookVerificationControllerTest.java
  be/ebook-search/ebook-web/src/test/java/com/meetyourbook/controller/LibraryControllerTest.java
  be/ebook-search/ebook-web/src/test/resources/org/springframework/restdocs/templates/asciidoctor/query-parameters.snippet
Labels: documentation, BE, testing, refactor

#54 [FE] 메인 페이지 스타일링 변경 및 로그인, 회원가입 스타일링
  .github/workflows/chromatic.yml
  fe/.storybook/preview.tsx
  fe/src/components/BackButton/BackButton.tsx
  fe/src/components/BooksDisplay/BookCard/BookCard.tsx
  fe/src/components/FilterDisplay/LibraryFilter/LibraryFilter.tsx
  fe/src/components/Navigation/DropDownBox/DropDownBox.tsx
  fe/src/components/Navigation/Navigation.tsx
  fe/src/hooks/useBooksLogic.tsx
  fe/src/mocks/handlers/booksHandler.ts
  fe/src/pages/Login.tsx
  fe/src/pages/SignUp.tsx
  fe/src/routers/routes.tsx
  fe/src/stories/Login.stories.tsx
  fe/src/stories/SignUp.stories.tsx
  fe/src/styles/AuthFormStyle.ts
  fe/src/styles/BookCardStyle.ts
  fe/src/styles/DropDownStyle.ts
  fe/src/styles/FilterDisplay.ts
  fe/src/styles/LibraryFilterStyle.ts
  fe/src/styles/LibraryListStyle.ts
  fe/src/styles/NavigationStyle.ts
  fe/src/styles/SearchInputStyle.ts
  fe/src/styles/ViewSelectorStyle.ts
  fe/src/tests/componentsTests/LibraryFilter.test.tsx
  fe/src/tests/componentsTests/Navgation.test.tsx
Labels: FE, refactor

#60 [BE] 크롤링 대상 도서관을 범위 지정방식으로 변경
  be/ebook-search/ebook-crawler/src/main/java/com/meetyourbook/controller/BookCrawlerController.java
  be/ebook-search/ebook-crawler/src/main/java/com/meetyourbook/dto/CrawlerRequest.java
  be/ebook-search/ebook-crawler/src/main/java/com/meetyourbook/service/BookCrawlerService.java
  be/ebook-search/ebook-crawler/src/test/java/com/meetyourbook/controller/BookCrawlerControllerTest.java
  be/ebook-search/ebook-crawler/src/test/java/com/meetyourbook/service/BookCrawlerServiceTest.java
  be/ebook-search/ebook-domain/src/main/java/com/meetyourbook/dto/LibraryCreationInfo.java
  be/ebook-search/ebook-domain/src/main/java/com/meetyourbook/repository/LibraryRepository.java
  be/ebook-search/ebook-domain/src/main/java/com/meetyourbook/service/LibraryDomainService.java
  be/ebook-search/ebook-web/src/main/java/com/meetyourbook/dto/LibraryCreateRequest.java
Labels: enhancement, BE

#57 [FE] 모바일 반응형 구현
  fe/src/components/BooksDisplay/BookCard/BookCard.tsx
  fe/src/components/Navigation/MobileSearchFilterPanel/MobileSearchFilterPanel.tsx
  fe/src/components/Navigation/Navigation.tsx
  fe/src/components/Navigation/SearchInput/SearchInput.tsx
  fe/src/pages/Home.tsx
  fe/src/pages/Login.tsx
  fe/src/pages/SignUp.tsx
  fe/src/stories/SearchInput.stories.tsx
  fe/src/styles/AuthFormStyle.ts
  fe/src/styles/BookCardStyle.ts
  fe/src/styles/BookDisplayStyle.ts
  fe/src/styles/FilterDisplay.ts
  fe/src/styles/MobileSearchFilterPanelStyle.ts
  fe/src/styles/NavigationStyle.ts
  fe/src/styles/SearchInputStyle.ts
  fe/src/tests/componentsTests/Navgation.test.tsx
  fe/src/tests/pagesTests/Layout.test.tsx
Labels: enhancement, FE

#63 [FE] ErrorBoundary, Suspense 구현 및 에러 수정
  fe/package-lock.json
  fe/package.json
  fe/src/components/BooksDisplay/BookCard/BookCard.tsx
  fe/src/components/BooksDisplay/BooksDisplay.tsx
  fe/src/components/ErrorFallBack/ErrorFallBack.tsx
  fe/src/components/FilterDisplay/LibraryFilter/LibraryFilter.tsx
  fe/src/components/LodingFallBack/LoadingFallBack.tsx
  fe/src/components/Navigation/Navigation.tsx
  fe/src/hooks/useBooksLogic.tsx
  fe/src/hooks/useQueryData.tsx
  fe/src/main.tsx
  fe/src/routers/routes.tsx
  fe/src/services/fetch.ts
  fe/src/styles/AuthFormStyle.ts
  fe/src/styles/DropDownStyle.ts
  fe/src/styles/ErrorFallBackStyle.tsx
  fe/src/styles/LibraryListStyle.ts
  fe/src/styles/NavigationStyle.ts
  fe/src/styles/ViewSelectorStyle.ts
  fe/src/styles/font.css
  fe/src/tests/componentsTests/BookCard.test.tsx
  fe/src/tests/componentsTests/BookDisplay.test.tsx
  fe/src/tests/componentsTests/Navgation.test.tsx
  fe/vite.config.ts
Labels: bug, enhancement, FE

#64 [BE] BookLibrary 데이터가 중복해서 저장되는 문제 해결
  be/ebook-search/ebook-crawler/src/test/java/com/meetyourbook/crawler/BookPageConcurrencyTest.java
  be/ebook-search/ebook-crawler/src/test/java/com/meetyourbook/crawler/BookPageProcessorTest.java
  be/ebook-search/ebook-domain/src/main/java/com/meetyourbook/config/JpaConfig.java
  be/ebook-search/ebook-domain/src/main/java/com/meetyourbook/dto/BookInfo.java
  be/ebook-search/ebook-domain/src/main/java/com/meetyourbook/entity/BaseEntity.java
  be/ebook-search/ebook-domain/src/main/java/com/meetyourbook/entity/Book.java
  be/ebook-search/ebook-domain/src/main/java/com/meetyourbook/entity/BookLibrary.java
  be/ebook-search/ebook-domain/src/main/java/com/meetyourbook/entity/Library.java
  be/ebook-search/ebook-domain/src/main/java/com/meetyourbook/repository/BookLibraryRepository.java
  be/ebook-search/ebook-domain/src/main/java/com/meetyourbook/service/BookLibraryService.java
  be/ebook-search/ebook-domain/src/test/java/com/meetyourbook/common/config/TestJpaConfig.java
  be/ebook-search/ebook-domain/src/test/java/com/meetyourbook/service/BookLibraryServiceTest.java
Labels: bug, BE

#69 [BE] book 및 book_library 저장 성능 개선
  be/ebook-search/ebook-crawler/src/main/java/com/meetyourbook/crawler/BookPageProcessor.java
  be/ebook-search/ebook-crawler/src/main/java/com/meetyourbook/service/BookCrawlerService.java
  be/ebook-search/ebook-crawler/src/main/java/com/meetyourbook/service/BookQueueService.java
  be/ebook-search/ebook-domain/src/main/java/com/meetyourbook/common/HibernateConfig.java
  be/ebook-search/ebook-domain/src/main/java/com/meetyourbook/common/QueryCountInspector.java
  be/ebook-search/ebook-domain/src/main/java/com/meetyourbook/dto/BookCache.java
  be/ebook-search/ebook-domain/src/main/java/com/meetyourbook/dto/BookLibraryPair.java
  be/ebook-search/ebook-domain/src/main/java/com/meetyourbook/entity/Book.java
  be/ebook-search/ebook-domain/src/main/java/com/meetyourbook/entity/BookLibrary.java
  be/ebook-search/ebook-domain/src/main/java/com/meetyourbook/repository/BookLibraryRepository.java
  be/ebook-search/ebook-domain/src/main/java/com/meetyourbook/repository/BookRepository.java
  be/ebook-search/ebook-domain/src/main/java/com/meetyourbook/service/BookLibraryService.java
  be/ebook-search/ebook-domain/src/test/java/com/meetyourbook/repository/BookRepositoryTest.java
  be/ebook-search/ebook-domain/src/test/java/com/meetyourbook/service/BookLibraryServiceTest.java
Labels: enhancement, BE

#68 [BE] Github Actions 워크 플로우 작성
  .github/workflows/deploy-web.yml
  be/ebook-search/ebook-web/Dockerfile
Labels: CI/CD

#66 [FE] 책 상세 팝업 기능 구현
  fe/src/components/BookInfoModal/BookInfoModal.tsx
  fe/src/components/BookInfoModal/LibrariesPaging.tsx
  fe/src/components/BooksDisplay/BookCard/BookCard.tsx
  fe/src/components/FilterDisplay/LibraryFilter/LibraryFilter.tsx
  fe/src/components/FilterDisplay/LibraryFilter/LibraryList.tsx
  fe/src/constants/index.ts
  fe/src/hooks/useOnClickOutside.tsx
  fe/src/services/fetch.ts
  fe/src/styles/BookCardStyle.ts
  fe/src/styles/BookInfoModalStyle.ts
  fe/src/styles/LibrariesPagingStyle.ts
  fe/src/tests/componentsTests/BookDisplay.test.tsx
  fe/src/tests/componentsTests/BookInfoModal.test.tsx
  fe/src/tests/componentsTests/LibrariesPaging.test.tsx
  fe/src/tests/hooksTests/useOnClickOutside.test.tsx
  fe/src/types/LibrariesResponse.ts
  fe/src/types/PageNation.ts
Labels: enhancement, FE

#72 [BE] 도커 파일 자바 JRE 변경
  be/ebook-search/ebook-web/Dockerfile
Labels: BE, CI/CD

#73 [BE] 도서관 정보를 크롤링하는 기능 구현
  be/ebook-search/ebook-crawler/src/main/java/com/meetyourbook/common/config/RestTemplateConfig.java
  be/ebook-search/ebook-crawler/src/main/java/com/meetyourbook/controller/LibraryCrawlerController.java
  be/ebook-search/ebook-crawler/src/main/java/com/meetyourbook/dto/CrawlerErrorResponse.java
  be/ebook-search/ebook-crawler/src/main/java/com/meetyourbook/dto/LibraryCrawlMetaData.java
  be/ebook-search/ebook-crawler/src/main/java/com/meetyourbook/dto/LibraryCrawlResponse.java
  be/ebook-search/ebook-crawler/src/main/java/com/meetyourbook/dto/LibraryCrawlResult.java
  be/ebook-search/ebook-crawler/src/main/java/com/meetyourbook/dto/LibraryCrawlerRequest.java
  be/ebook-search/ebook-crawler/src/main/java/com/meetyourbook/dto/SimpleLibraryInfo.java
  be/ebook-search/ebook-crawler/src/main/java/com/meetyourbook/service/LibraryCrawlerService.java
  be/ebook-search/ebook-crawler/src/test/java/com/meetyourbook/controller/LibraryCrawlerControllerTest.java
Labels: enhancement, BE

#75 [BE] 기존에 web-api를 어드민 및 유저 api로 분리했습니다.
  be/ebook-search/ebook-web/src/docs/asciidoc/admin-book.adoc
  be/ebook-search/ebook-web/src/docs/asciidoc/admin-library.adoc
  be/ebook-search/ebook-web/src/docs/asciidoc/admin-verification.adoc
  be/ebook-search/ebook-web/src/docs/asciidoc/book.adoc
  be/ebook-search/ebook-web/src/docs/asciidoc/index.adoc
  be/ebook-search/ebook-web/src/docs/asciidoc/library.adoc
  be/ebook-search/ebook-web/src/main/java/com/meetyourbook/controller/BookController.java
  be/ebook-search/ebook-web/src/main/java/com/meetyourbook/controller/LibraryController.java
  be/ebook-search/ebook-web/src/main/java/com/meetyourbook/controller/admin/AdminBookController.java
  be/ebook-search/ebook-web/src/main/java/com/meetyourbook/controller/admin/AdminLibraryController.java
  be/ebook-search/ebook-web/src/main/java/com/meetyourbook/controller/admin/BookVerificationController.java
  be/ebook-search/ebook-web/src/test/java/com/meetyourbook/controller/BookControllerTest.java
  be/ebook-search/ebook-web/src/test/java/com/meetyourbook/controller/LibraryControllerTest.java
  be/ebook-search/ebook-web/src/test/java/com/meetyourbook/controller/admin/AdminBookControllerTest.java
  be/ebook-search/ebook-web/src/test/java/com/meetyourbook/controller/admin/AdminLibraryControllerTest.java
  be/ebook-search/ebook-web/src/test/java/com/meetyourbook/controller/admin/BookVerificationControllerTest.java
Labels: documentation, BE, refactor

#76 [BE] 도서관 검색 api로부터 도서관 정보를 db에 저장
  be/ebook-search/ebook-crawler/src/main/java/com/meetyourbook/controller/LibraryCrawlerController.java
  be/ebook-search/ebook-crawler/src/main/java/com/meetyourbook/dto/KyoboLibraryApiRequest.java
  be/ebook-search/ebook-crawler/src/main/java/com/meetyourbook/dto/LibraryCrawlResult.java
  be/ebook-search/ebook-crawler/src/main/java/com/meetyourbook/service/LibraryCrawlerService.java
  be/ebook-search/ebook-domain/src/main/java/com/meetyourbook/dto/LibraryCreationInfo.java
  be/ebook-search/ebook-domain/src/main/java/com/meetyourbook/service/LibraryDomainService.java
  be/ebook-search/ebook-domain/src/test/java/com/meetyourbook/service/LibraryDomainServiceTest.java
  be/ebook-search/ebook-web/src/main/java/com/meetyourbook/dto/LibraryCreateRequest.java
Labels: enhancement, BE

#71 [BE] 크롤링 결과를 저장하는 로직 리팩터링
  .github/workflows/build.yml
  be/ebook-search/ebook-crawler/build.gradle
  be/ebook-search/ebook-crawler/src/main/java/com/meetyourbook/config/CachingConfig.java
  be/ebook-search/ebook-crawler/src/main/java/com/meetyourbook/dto/BookLibraryRelation.java
  be/ebook-search/ebook-crawler/src/main/java/com/meetyourbook/dto/BookRecord.java
  be/ebook-search/ebook-crawler/src/main/java/com/meetyourbook/dto/BookUniqueKey.java
  be/ebook-search/ebook-crawler/src/main/java/com/meetyourbook/repository/BookJdbcRepository.java
  be/ebook-search/ebook-crawler/src/main/java/com/meetyourbook/repository/BookLibraryJdbcRepository.java
  be/ebook-search/ebook-crawler/src/main/java/com/meetyourbook/service/BookCacheService.java
  be/ebook-search/ebook-crawler/src/main/java/com/meetyourbook/service/BookLibraryService.java
  be/ebook-search/ebook-crawler/src/main/java/com/meetyourbook/service/BookQueueService.java
  be/ebook-search/ebook-crawler/src/main/java/com/meetyourbook/service/LibraryCacheService.java
  be/ebook-search/ebook-crawler/src/test/java/com/meetyourbook/repository/BookJdbcRepositoryTest.java
  be/ebook-search/ebook-crawler/src/test/java/com/meetyourbook/repository/BookLibraryJdbcRepositoryTest.java
  be/ebook-search/ebook-crawler/src/test/resources/application.yaml
  be/ebook-search/ebook-domain/src/main/java/com/meetyourbook/dto/BookCache.java
  be/ebook-search/ebook-domain/src/main/java/com/meetyourbook/dto/BookLibraryPair.java
  be/ebook-search/ebook-domain/src/main/java/com/meetyourbook/repository/BookRepository.java
  be/ebook-search/ebook-domain/src/main/java/com/meetyourbook/service/BookLibraryService.java
  be/ebook-search/ebook-domain/src/test/java/com/meetyourbook/repository/BookRepositoryTest.java
Labels: BE, refactor

#78 [BE] actions-workflow파일 개선
  .github/workflows/deploy-web.yml
  .github/workflows/sonarcloud-analysis.yml
Labels: BE, refactor, CI/CD
